config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  
  scope module: :users do
    resources :ingredients do
      resources :comments, only: [:create, :update]
    end
    resources :genres, except: [:new]
    get 'users/mypage' => 'users#show'
    get 'users/mypage/edit' => 'users#edit'
    patch 'users/mypage' => 'users#update', as: 'update_user'
    
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  
  #検索機能
  get "search" => "searches#search"
  get "search_by_date" => "searches#search_by_date"
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
    @range = params[:range]

    if @range == "Genre"
      @genres = Genre.looks(params[:search], params[:name])
    else
      @ingredients = Ingredient.looks(params[:search], params[:name])
    end
    @comment = Comment.new
  end
  
  def search_by_date
    # Time.currentで、JST(application.rbで指定したタイムゾーン)の時刻を取得
    # 文字列に変換後、Date.parseで日付に戻す
    @start_date = Date.parse(Time.current.to_s)
    #賞味期限検索の場合
    if params[:method] == "expiration"
      #今日から◯日後
      @end_date = @start_date + params[:date].to_i
      @ingredients = Ingredient.where(expiration_date: @start_date..@end_date).order(expiration_date: :asc)
    #購入日検索の場合
    elsif params[:method] == "purchase"
      #今日から◯日前
      @end_date = @start_date - params[:date].to_i
      @ingredients = Ingredient.where(purchase_date: @end_date..@start_date).order(purchase_date: :asc)
    else
      @ingredients = Ingredient.where("expiration_date < ?", @start_date).order(purchase_date: :asc)
    end
    @comment = Comment.new
  end
  
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_form.html.erb
<!--検索機能 -->
<% if user_signed_in? %>
  <div class="d-flex justify-content-start">
    <div class="search_form mx-5 mb-3">
    検索
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :name, value: params[:name] %>
      <%= f.select :range, [['ジャンル', 'Genre'], ['食材', 'Ingredient']], {selected: params[:range]} %>
      <%= f.select :search, [["完全一致","perfect_match"], ["部分一致","partial_match"], ["前方一致","forward_match"], ["後方一致","backward_match"]], {selected: params[:search]} %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
    </div>
<!--賞味期限、購入日　検索機能 --> 
    <div class="search_form mb-3">
    日付け検索
    <%= form_with url: search_by_date_path, local: true, method: :get do |f| %>
      <%= f.select :method, [["賞味期限", "expiration"], ["賞味期限切れ", "out_of_expiration"], ["購入日", "purchase"]], {selected: params[:method]} %>
      <%= f.select :date, (0..7).map{|day| [day == 0 ? "本日" : "#{day}日前", day]}, {selected: params[:date]} %>
  　　<%= f.submit '検索', class: 'btn btn-primary'  %>
　　<% end %>
    </div>
  </div>
<% end %>

<script>
  // ページがロードされた時
  $(document).ready(function () {
    // 検索メソッドが、賞味期限切れが選択されていれば
    if ($("#method").val() == "out_of_expiration") {
      $("#date").hide(); // 日付選択を隠す
    } else {
      $("#date").show(); // 日付選択を出す
    }
  });
  
  // 検索メソッドが、変更された時
  $("#method").change(function () {
    // 賞味期限切れの項目が選択されているかどうかで
    if ($(this).val() == "out_of_expiration") {
      $("#date").hide(); // 日付選択を隠す
    } else {
      $("#date").show(); // 日付選択を出す
    }
  });
</script>

app/views/searches/_serach.html.erb
<!--検索機能 -->
<% if user_signed_in? %>
  <div class="search_form">
    <%= form_with url: search_path, local: true, method: :get do |f| %>
      <%= f.text_field :name %>
      <%= f.select :range, options_for_select([['Genre'], ['Ingredient']]) %>
      <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
      <%= f.submit "検索", class: "btn btn-primary" %>
    <% end %>
  </div>
<% end %>

app/views/searches/search.html.erb
<div class="my-4">
<h2>検索結果</h2>

<table class="table table-hover table-inverse">
  <!--検索対象モデルがGenreの時 -->
<% if @range == "Genre" %>
  <% if @genres.present? %>
     <tbody>
      <% if params[:name].blank? %>
        <tr>
          <td><%= link_to "なし", genre_path(0) %></td>
        </tr>
      <% end %>
      <% @genres.each do |genre| %>
        <tr>
          <td><%= link_to genre.name, genre_path(genre) %></td>
        </tr>
      <% end %>
     </tbody>
  <% else %>
     <div class="text-center">該当するジャンルは登録されていません。</div>
     登録する場合は<%= link_to "こちら", genres_path %>から登録してください。
  <% end %>  
<% else %>
    <!--検索対象モデルがGenreではない時(= 検索対象モデルがIngredientの時) -->
  <% if @ingredients.present? %>
    <thead>
		    <tr>
		      <th>食材</th>
		      <th>ジャンル</th>
	      	<th>購入日</th>
		      <th>賞味期限</th>
		      <th>数量</th>
		      <th>メモ</th>
		    </tr>
	  </thead>
    <tbody>
      <% @ingredients.each do |ingredient| %>
        <tr>
         <td><%= ingredient.name %></td>
         <td><%= ingredient.genre.nil? ? "なし" : ingredient.genre.name %></td>
         <td><%= ingredient.purchase_date.blank? ? "" : ingredient.purchase_date.strftime("%Y/%m/%d") %></td>
         <td><%= ingredient.expiration_date.blank? ? "" : ingredient.expiration_date.strftime("%Y/%m/%d") %></td>
         <td><%= ActiveSupport::NumberHelper.number_to_rounded(ingredient.quantity, strip_insignificant_zeros: true) %><%= ingredient.unit %></td>
         <td>
             <% comment = ingredient.comments.first || @comment %>
                <%= form_with model: [ingredient, comment] do |f| %>
                  <%= f.text_area :comment, rows: '2', placeholder: "メモ" %>
                  <%= f.submit "メモを更新する" %>
                <% end %>
         </td>
        </tr>
       <% end %>
      </tbody>
    </table>
  <% else %>
    <div class="text-center">該当する食材は登録されていません。</div>
    登録する場合は<%= link_to "こちら", new_ingredient_path %>から登録してください。
  <% end %>
<% end %>
</div>

app/views/searches/search_by_date.html.erb
 <div class="my-4">
 <div class="text-center"><h2>検索結果</h2></div>
<% if @ingredients.present? %>
  
　<% if params[:method] == "expiration" %><!-- 賞味期限検索の場合 -->
    <h5><%= @start_date.strftime("%Y年%m月%d日") %>～<%= @end_date.strftime("%Y年%m月%d日") %>に賞味期限を迎えるもの</h5>
  <% elsif params[:method] == "purchase" %><!-- 購入日検索の場合 -->
    <h5><%= @end_date.strftime("%Y年%m月%d日") %>～<%= @start_date.strftime("%Y年%m月%d日") %>に購入したもの</h5>
  <% else %>
    <h5>賞味期限切れ</h5>
　<% end %>
   <table class="table table-hover table-inverse">
     <thead>
		    <tr>
		      <th>食材</th>
		      <th>ジャンル</th>
	      	  <th>購入日</th>
		      <th>賞味期限</th>
		      <th>数量</th>
		      <th>メモ</th>
		    </tr>
	  </thead>
      <tbody>
      <% @ingredients.each do |ingredient| %>
        <tr>
         <td><%= ingredient.name %></td>
         <td><%= ingredient.genre.nil? ? "なし" : ingredient.genre.name %></td>
         <td><%= ingredient.purchase_date.blank? ? "" : ingredient.purchase_date.strftime("%Y/%m/%d") %></td>
         <td>
                  <% unless ingredient.expiration_date.blank? %>
                    <% if ingredient.expiration_date > Date.today %>
                      <%= ingredient.expiration_date.strftime("%Y/%m/%d") %>
                    <% else %>  <!-- 賞味期限が過ぎていた場合-->     
                  <span class="text-danger font-weight-bold">
                      <%= ingredient.expiration_date.strftime("%Y/%m/%d") %><br>[賞味期限切れ]
                  </span>
                    <% end %>
                  <% end %>
         </td>
         <td><%= ActiveSupport::NumberHelper.number_to_rounded(ingredient.quantity, strip_insignificant_zeros: true) %><%= ingredient.unit %></td>
         <td>
              <% comment = ingredient.comments.first || @comment %>
                <%= form_with model: [ingredient, comment] do |f| %>
                  <%= f.text_area :comment, rows: '2', placeholder: "メモ" %>
                  <%= f.submit "メモを更新する" %>
                <% end %>
         </td>
        </tr>
       <% end %>
       </tbody>
   </table>
<% else %>
   <div class="text-center">該当する食材は登録されていません。<br>
    登録する場合は<%= link_to "こちら", new_ingredient_path %>から登録してください。</div>
<% end %>
</div>

app/views/searches/search_result.html.erb
<h2>検索結果</h2>

<table class="table table-hover table-inverse">
  <!--検索対象モデルがGenreの時 -->
  <% if @range == "Genre" %>
    <tbody>
      <% @genres.each do |genre| %>
        <tr>
          <td><%= genre.name %></td>
        </tr>
      <% end %>
    </tbody>
  <% else %>
    <!--検索対象モデルがGenreではない時(= 検索対象モデルがIngredientの時) -->
    <tbody>
      <% @ingredients.each do |ingredient| %>
        <tr>
         <td><%= ingredient.name %></td>
         <td><%= ingredient.purchase_date %></td>
         <td><%= ingredient.expiration_date %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>