config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  
  scope module: :users do
    resources :ingredients do
      resources :comments, only: [:create, :update]
    end
    resources :genres, except: [:new]
    get 'users/mypage' => 'users#show'
    get 'users/mypage/edit' => 'users#edit'
    patch 'users/mypage' => 'users#update', as: 'update_user'
    
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  
  #検索機能
  get "search" => "searches#search"
  get "search_by_date" => "searches#search_by_date"
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :genre, optional: true
	belongs_to :user
	
	has_many :comments, dependent: :destroy
    
  validates :user_id, :name, :quantity, presence: true
  validates :quantity, numericality: { only_float: true }
  
  # 並び替え機能
  scope :name_sort, -> {order(name: :asc)}
  # 登録の新しい順、古い順
  scope :latest, -> {order(created_at: :desc)}
  scope :old, -> {order(created_at: :asc)}
  # 購入日の新しい順、古い順
  scope :purchase_date_latest, -> {order(Arel.sql("purchase_date DESC NULLS LAST"))}
  scope :purchase_date_old, -> {order(Arel.sql("purchase_date ASC NULLS LAST"))}
  # 賞味期限の早い順、遅い順
  scope :expiration_date_latest, -> {order(Arel.sql("expiration_date ASC NULLS LAST"))}
  scope :expiration_date_old, -> {order(Arel.sql("expiration_date DESC NULLS LAST"))}
  
  
  # 検索方法分岐
  def self.looks(search, name)
    if search == "perfect_match"
      @ingredient = Ingredient.where("name LIKE?", "#{name}")
    elsif search == "forward_match"
      @ingredient = Ingredient.where("name LIKE?","#{name}%")
    elsif search == "backward_match"
      @ingredient = Ingredient.where("name LIKE?","%#{name}")
    elsif search == "partial_match"
      @ingredient = Ingredient.where("name LIKE?","%#{name}%")
    else
      @ingredient = Ingredient.all
    end
  end
  
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :genres, dependent: :destroy
  has_many :ingredients, dependent: :destroy
  
  with_options presence: true do
    validates :last_name
    validates :first_name
    validates :last_name_kana
    validates :first_name_kana
  end
end

app/controllers/users/comments_controller.rb
class Users::CommentsController < ApplicationController
  before_action :authenticate_user!
    
  def create
    ingredient = Ingredient.find(params[:ingredient_id])
    comment = ingredient.comments.new(comment_params)
    comment.save
    redirect_to request.referer
  end
  
  def update
    comment = Comment.find(params[:id])
    comment.update(comment_params)
    redirect_to request.referer
  end
  
  private

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/genres_controller.rb
class Users::GenresController < ApplicationController
  before_action :authenticate_user!
  
  def index
    case params[:sort]
    when "name_sort" then #50音順
                                              #漢字、カタカナをひらがなに変換して並べる
       @genres = current_user.genres.sort_by {|i| [i.name.to_kanhira.to_hira, i]}
    when "date_sort_latest" then #登録が新しい順
       @genres = current_user.genres.latest
    when "date_sort_old" then #登録が古い順
       @genres = current_user.genres.old
    else
       @genres = current_user.genres
    end
    
    @genre = Genre.new
  end
   
  def create
    @genre = Genre.new(genre_params)
    @genre.user_id = current_user.id
    if @genre.save
      redirect_to genres_path
    else
      @genres = current_user.genres
      render :index
    end
  end
  
  def show
    if params[:id].to_i == 0  #idが0ならnil=ジャンル"なし"
        @ingredients = Ingredient.where(user_id: current_user.id, genre: nil)
    else
        @genre = Genre.find(params[:id])
        @ingredients = @genre.ingredients #ジャンルに属した食材
    end
     case params[:sort]
     when "name_sort" then #50音順
                                          #漢字、カタカナをひらがなに変換して並べる
      @ingredients = @ingredients.sort_by {|i| [i.name.to_kanhira.to_hira, i]}
     when "date_sort_latest" then #登録が新しい順
      @ingredients = @ingredients.latest
     when "date_sort_old" then #登録が古い順
      @ingredients = @ingredients.old
     when "purchase_date_latest" then #購入日が新しい順
      @ingredients = @ingredients.purchase_date_latest
     when "purchase_date_old" then #購入日が古い順
      @ingredients = @ingredients.purchase_date_old
     when "expiration_date_latest" then #賞味期限が遠い順
      @ingredients = @ingredients.expiration_date_latest
     when "expiration_date_old" then #賞味期限が近い順
      @ingredients = @ingredients.expiration_date_old
     else
      @ingredients = @ingredients
     end
    #食材のメモ機能
    @comment = Comment.new
  end

  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    genre = Genre.find(params[:id])
    genre.update(genre_params)
    redirect_to genre_path(genre.id)
  end
  
  def destroy
    genre = Genre.find(params[:id])
    genre.destroy
    redirect_to genres_path
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/users/ingredients_controller.rb
class Users::IngredientsController < ApplicationController
  before_action :authenticate_user!
  
  def index
    case params[:sort]
    when "name_sort" then #50音順
                                                                              #漢字、カタカナをひらがなに変換して並べる
      @ingredients = Kaminari.paginate_array(current_user.ingredients.sort_by {|i| [i.name.to_kanhira.to_hira, i]}).page(params[:page])
    when "date_sort_latest" then #登録が新しい順
      @ingredients = current_user.ingredients.latest.page(params[:page])
    when "date_sort_old" then #登録が古い順
      @ingredients = current_user.ingredients.old.page(params[:page])
    when "purchase_date_latest" then #購入日が新しい順
      @ingredients = current_user.ingredients.purchase_date_latest.page(params[:page])
    when "purchase_date_old" then #購入日が古い順
      @ingredients = current_user.ingredients.purchase_date_old.page(params[:page])
    when "expiration_date_latest" then #賞味期限が遠い順
      @ingredients = current_user.ingredients.expiration_date_latest.page(params[:page])
    when "expiration_date_old" then #賞味期限が近い順
      @ingredients = current_user.ingredients.expiration_date_old.page(params[:page])
    else
      @ingredients = current_user.ingredients.page(params[:page])
    end
    #食材のメモ機能
    @comment = Comment.new
  end
  
  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    @ingredient.genre_id = ingredient_params[:genre_id].blank? ? nil : ingredient_params[:genre_id]
    @ingredient.user_id = current_user.id
    if @ingredient.save
      redirect_to @ingredient.genre_id.nil? ? genre_path(0) : genre_path(@ingredient.genre)
    else
      flash.now[:alert] = "必要事項が入力されていません。"
      render :new
    end
  end

  def edit
    @ingredient = Ingredient.find(params[:id])
  end
  
  def update
    @ingredient = Ingredient.find(params[:id])
    if @ingredient.update(ingredient_params)
      redirect_to @ingredient.genre_id.nil? ? genre_path(0) : genre_path(@ingredient.genre)
    else
      flash.now[:alert] = "必要事項が入力されていません。"
      render :edit
    end
  end
  
  def destroy
    ingredient = Ingredient.find(params[:id])
    ingredient.destroy
    redirect_to request.referer
  end
  
  private
  
  def ingredient_params
    params.require(:ingredient).permit(
      :genre_id, :name, :expiration_date, :purchase_date, :quantity, :unit
    )
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/users_controller.rb
class Users::UsersController < ApplicationController
    before_action :authenticate_user!
    
    def show
      @user = current_user
    end
    
    def edit
      @user = current_user
    end
  
    def update
      @user = current_user
      if @user.update(user_params)
         redirect_to users_mypage_path
      else
         flash.now[:alert] = "必要事項が入力されていません。"
         render 'edit'
      end
    end
    
    private
    def user_params
        params.require(:user).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :email, )
    end

     
end

app/helpers/users/comments_helper.rb
module Users::CommentsHelper
end

app/helpers/users/genres_helper.rb
module Users::GenresHelper
end

app/helpers/users/ingredients_helper.rb
module Users::IngredientsHelper
end

app/helpers/users/users_helper.rb
module Users::UsersHelper
end

app/views/users/ingredients/edit.html.erb
<div class="my-4">
<h2>食材データ　編集</h2>
<%= render 'layouts/errors', errors: @ingredient %>

<%= form_with model: @ingredient do |f| %>
 
 <div class="form-group">
        <%= f.label :ジャンル %><font color="red">*必須</font>
        <%= f.collection_select(:genre_id, current_user.genres, :id, :name, include_blank: "なし") %>
    </div>
    <div class="form-group">
        <%= f.label :食材 %><font color="red">*必須</font>
        <%= f.text_field :name %>
    </div>
    <div class="form-group">
        <%= f.label :購入日 %>
        <%= f.date_field :purchase_date %>
    </div>
    <div class="form-group">
        <%= f.label :賞味期限 %>
        <%= f.date_field :expiration_date %>
    </div>
    <div class="form-group">
        <%= f.label :数量 %><font color="red">*必須</font>
        <%= f.number_field :quantity, step: 0.1 %>
    </div>
    <div class="form-group">
        <%= f.label :単位 %>
        <%= f.text_field :unit %>
    </div>
 
 <%= f.submit '更新する', class: "btn btn-success" %>
  
<% end %>
</div>

app/views/users/ingredients/index.html.erb
<div class="my-4">
<% if @ingredients.present? %>
<h2>食材一覧</h2>
  <%= form_with url: ingredients_path, method: :get do |f| %>
    <%= f.select :sort, 
          [
            ["50音順", "name_sort"],
            ["登録日が新しい順", "date_sort_latest"],
            ["登録日が古い順", "date_sort_old"],
            ["購入日が新しい順", "purchase_date_latest"],
            ["購入日が古い順", "purchase_date_old"],
            ["賞味期限が早い順", "expiration_date_latest"],
            ["賞味期限が遅い順", "expiration_date_old"],
          ], {selected: params[:sort]}
    %>
    <%= f.submit "並び替え", class: "btn btn-primary btn-sm mr-3" %>
    <% end %>
 
  <table class="table table-hover table-bordered table-condensed">
      <thead>
		    <tr>
		      <th>食材</th>
		      <th>ジャンル</th>
	      	　<th>購入日</th>
		      <th>賞味期限</th>
		      <th>数量</th>
		      <th>メモ</th>
		      <th></th>
		      <th></th>
		    </tr>
      </thead>
      <tbody>
        <% @ingredients.each do |ingredient| %>
            <tr>
              <td><%= ingredient.name %></td>
              <td><%= ingredient.genre.nil? ? "なし" : ingredient.genre.name %></td>
              <!-- 日付設定がされていない場合blank、されている場合は表示する-->
              <td><%= ingredient.purchase_date.blank? ? "" : ingredient.purchase_date.strftime("%Y/%m/%d") %></td>
              <td>
                <% unless ingredient.expiration_date.blank? %>
                  <% if ingredient.expiration_date > Date.today %>
                    <%= ingredient.expiration_date.strftime("%Y/%m/%d") %>
                  <% else %>  <!-- 賞味期限が過ぎていた場合-->     
                    <span class="text-danger font-weight-bold">
                      <%= ingredient.expiration_date.strftime("%Y/%m/%d") %><br>[賞味期限切れ]
                    </span>
                  <% end %>
                <% end %>
              </td>
              <td><%= ActiveSupport::NumberHelper.number_to_rounded(ingredient.quantity, strip_insignificant_zeros: true) %><%= ingredient.unit %></td>
              <td>
                <% comment = ingredient.comments.first || @comment %>
                 <%= form_with model: [ingredient, comment] do |f| %>
                  <%= f.text_area :comment, rows: '2', placeholder: "メモ" %>
                  <%= f.submit "メモを更新する", class: "btn btn-light" %>
                 <% end %>
              </td>
              <td><%= link_to "編集する", edit_ingredient_path(ingredient.id), class: "btn btn-success" %></td>
              <td><%= link_to "削除する", ingredient_path(ingredient.id), method: :delete, 
                  "data-confirm" => "本当に削除しますか？", class: "btn btn-danger" %></td>
    　　<% end %>
    　</tbody>
    </table>
    　<div class="d-flex justify-content-center"><%= paginate @ingredients %></div>
<% else %>
    <div class="text-center">現在食材は登録されていません。<br>
    登録する場合は<%= link_to "こちら", new_ingredient_path %>から登録してください。</div>
<% end %>
</div>
 

app/views/users/ingredients/new.html.erb
<h2>食材　登録</h2>
<%= render 'layouts/errors', errors: @ingredient %>

<%= form_with model: @ingredient, url: ingredients_path, method: :post do |f| %>
    <div class="form-group">
        <%= f.label :ジャンル %><font color="red">*必須</font>
        <%= f.collection_select(:genre_id, current_user.genres, :id, :name, include_blank: "なし") %>
    </div>
    <div class="form-group">
        <%= f.label :食材 %><font color="red">*必須</font>
        <%= f.text_field :name %>
    </div>
    <div class="form-group">
        <%= f.label :購入日 %>
        <%= f.date_field :purchase_date %>
    </div>
    <div class="form-group">
        <%= f.label :賞味期限 %>
        <%= f.date_field :expiration_date %>
    </div>
    <div class="form-group">
        <%= f.label :数量 %><font color="red">*必須</font>
        <%= f.number_field :quantity, step: 0.1 %>
    </div>
    <div class="form-group">
        <%= f.label :単位 %>
        <%= f.text_field :unit %>
    </div>
    
    <div class="form-group">
        <%= f.submit "登録" %>
    </div>
    
<% end %>

app/views/users/ingredients/show.html.erb
<h1>Users::Ingredients#show</h1>
<p>Find me in app/views/users/ingredients/show.html.erb</p>