config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  
  scope module: :users do
    resources :ingredients do
      resources :comments, only: [:create, :update]
    end
    resources :genres, except: [:new]
    get 'users/mypage' => 'users#show'
    get 'users/mypage/edit' => 'users#edit'
    patch 'users/mypage' => 'users#update', as: 'update_user'
    
  end
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  
  #検索機能
  get "search" => "searches#search"
  get "search_by_date" => "searches#search_by_date"
end

app/views/layouts/_errors.html.erb
<% if errors.errors.any? %>
    <ul>
        <% errors.errors.full_messages.each do |error| %>
            <li class="text-danger font-weight-bold"><%= error %></li>
        <% end %>
    </ul>
<% end %>

app/views/layouts/_header.html.erb
 <header class="p-2">
<% if user_signed_in? %>
        <h1><%= link_to "食財リスト", root_path %></h1>
        <div class="text-right">こんにちは、<%= current_user.last_name + current_user.first_name %>さん</div>
        
        <h5><%= I18n.l(Date.parse(Time.current.to_s), format: :long) %></h5>
        
        <%= link_to "ログアウト", destroy_user_session_path,class:"mx-2 bg-white font-weight-bold", method: :delete %>
        <%= link_to "マイページ", users_mypage_path,class:"mx-2 bg-white font-weight-bold" %>
        <%= link_to "食材登録", new_ingredient_path,class:"mx-2 bg-white font-weight-bold" %>
        <%= link_to "食材一覧", ingredients_path,class:"mx-2 bg-white font-weight-bold" %>
        <%= link_to "ジャンル", genres_path,class:"mx-2 bg-white font-weight-bold" %>
    
      
<% else %>
        <h1><%= link_to "食財リスト", root_path %></h1>
        
        <%= link_to "初めての方はこちらへ", new_user_registration_path,class:"mx-2 bg-white font-weight-bold" %>
        <%= link_to "ログイン", new_user_session_path,class:"mx-2 bg-white font-weight-bold" %>
      
<% end %>
 </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>食財リスト</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <div class="container-fluid">
    <header style="background-color: #FFCCCC;">
     <%= render 'layouts/header' %>
     <!--検索機能 -->
     <%= render 'searches/form' %>
    </header>
    <% if flash[:alert] %>
        <div class="alert alert-danger mt-3" role="alert">
          <%= flash[:alert] %>
        </div>
    <% end %>
    <%= yield %>
   </div>
  </body>
</html>